### ISSUE TITLE
Add ability to use `private` disks

### ISSUE THREAD

**Issue by milewski** [BBS-Lab/nova-file-manager#54]
Hi currently it's impossible to use private cloud disks.. for instance, this is how it is used with default nova image/file fields:

```php
Image::make('Image', 'image->file')
    ->storeOriginalName('image->filename')
    ->disk('s3-private')
    ->preview(fn (string $file, string $disk) => Storage::disk($disk)->temporaryUrl($file, now()->addMinute()))
    ->thumbnail(fn (string $file, string $disk) => Storage::disk($disk)->temporaryUrl($file, now()->addMinute()))
    ->creationRules('required')
    ->updateRules('nullable'),
```

---
Here is a quickly docker-compose snipped to start a "local s3" if this helps develop this feature

```yaml
  minio:
    image: bitnami/minio:2022
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=secret-password
      - MINIO_DEFAULT_BUCKETS=development-public:public,development-private:none
```
